#! /usr/bin/env ruby

require 'autotest/restart'

Autotest.add_hook :initialize do |autotest|
  autotest.sleep = 1
  %w{.git .svn .hg .DS_Store ._* vendor :2e_ .AppleDouble .scss .sass .css tmp log doc}.each do |exception|
    autotest.add_exception(exception)
  end
end
